### ISSUE TITLE
Spark-based distributed transformers implementation.

### ISSUE THREAD

**Issue by fonhorst** [fonhorst/LightAutoML_Spark#16]
The following transformers should be implemented using Spark SQL functions:
- [x] #25
- [x] #23
- [x] #24
- [x] #26
- [x] #27
- [x] #28
- [ ] ~~TunableTransformer~~ (No need to rewrite but may be some refactoring is neccessary)
- [x] #29
- [x] #30
- [x] #31
- [x] #32
- [x] #33
- [ ] ~~SequentialTransformer~~ (only applies other transformers, no need to rewrite)
- [ ] UnionTransformer (multiproc impl ?)
- [ ] ~~ColumnwiseUnion~~ (only applies other transformers, no need to rewrite)
- [ ] ~~ColumnsSelector~~ (works only with metadata, no need to rewrite, but requires support from SparkDataset - columns subselecting with the slice syntax)
- [ ] ~~BestOfTransformers~~  (applies other transformers and a criterion function to the resulting dataset, appropriate modifications should be done in pipelines)
- [ ] ~~ConvertDataset~~ (all modifications is required only for SparkDataset)
- [ ] ~~ChangeRoles~~ (all modifications is required only for SparkDataset)
- [x] #34
- [x] #35
- [x] #36
- [x] #37
- [x] #38
- [x] #39
- [x] #40
- [x] #41
- [x] #42
- [x] #43
- [x] #44
- [x] #45
- [x] #47
- [x] #46
